services:

  apibox:
    image: "mcr.microsoft.com/azure-databases/data-api-builder:latest"
    restart: on-failure
    volumes:
      - "./startrek.json:/App/dab-config.json"
    ports:
      - "5000:5000"
    depends_on:
      - sqlDatabase

  sqlDatabase:
    image: mcr.microsoft.com/mssql/server
    container_name: trekdb
    hostname: sqltrek
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1rootP@ssword"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    volumes:
      - ./startrek.sql:/startrek.sql
      - ./run-initialization.sh:/run-initialization.sh
    command: ./run-initialization.sh